version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: punchpass-api
    ports:
      - "8000:8000"
      - "9222:9222"
    volumes:
      - ./src:/code/src
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SBR_WS_CDP=${SBR_WS_CDP}
    command: python src/main.py
